#%RAML 1.0
title: StarWars Character API
version: v1
baseUri: http://api.example.com/starwars

/characters:
  get:
    description: Retrieve all Star Wars characters and export as CSV.
    queryParameters:
      gender:
        description: Filter characters by gender.
        type: string
        required: false
        enum: [male, female, unknown, "n/a"]
        example: female
    responses:
      200:
        description: Successful response with a CSV file containing character information.
        body:
          text/csv:
            example: !include samples/response-200.csv
      400:
        description: Bad request due to invalid query parameter.
        body:
          application/json:
            example: !include samples/response-400.json
      500:
        description: Internal server error.
        body:
          application/json:
            example: !include samples/response-500.json
